#!/bin/sh
# prerm script for lliurex-inventory-agent
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case $1 in
	remove|purge|abort-install|disappear)
		# check if actual file is a symbolic link and remove it
		# check existence of diverted file and remove diversion
        	# restart service if it is running
		lliurex-inventory-cli unconfigure

		;;

	*)
		echo "Nothing to do"
		;;
esac

#DEBHELPER#

exit 0

