#!/bin/bash

ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	postInstall)

		TEST=$(dpkg-query -s lliurex-inventory-agent 2> /dev/null | grep Status | cut -d " " -f 4)

		if [ "$TEST" == 'installed' ];then
			TEST=$(dpkg-query -s fusioninstall 2> /dev/null | grep Status | cut -d " " -f 4)
			if [ $TEST == 'installed' ];then
				apt-get remove -y fusioninstall
			fi
		fi

	;;

	remove)
		count=0
		for ix in $PACKAGE_LIST
		do
			apt-get remove -y $ix

			TEST=$(dpkg-query -s $ix 2> /dev/null | grep Status | cut -d " " -f 4)

			if [ "$TEST" == 'installed' ];then
				count+=1
			fi
		done

		if [ $count -gt 0 ];then
			exit 1
		fi
	;;

esac
exit 0	
